apiVersion: redis.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: redis/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    availabilityZone: ap-hongkong-1
    memSize: 8192
    name: terrform_test
    passwordSecretRef:
      key: credentials
      name: example-creds
      namespace: default
    port: 6379
    redisReplicasNum: 1
    redisShardNum: 1
    subnetId: subnet-8fffi4nf
    typeId: 2
    vpcId: vpc-p1va48nq

