apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: redis/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ap-hongkong-1
    cidrBlock: 10.0.1.0/24
    name: tf_redis_subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

